#Only edit the link below if you have YOURLS installed on a server that you own and configured it properly
api-link: http://begr.im/yourls-api.php?signature=26dc86d493&action=shorturl&url=

#MAKE SURE ONLY ONE IS TRUE, OR BOTH ARE FALSE. DO NOT RUN WHILE THEY ARE BOTH TRUE
blacklist-boolean: false
whitelist-boolean: false

blacklist:
  - www.pornhub.com
  - www.bing.ca
whitelist:
  - www.google.ca