name: ShortIt
main: net.targetcraft.shortit.MainClass
version: 0.7
description: ShortIt
author: aman207

commands:
    link:
     description: General command for all of ShortIt's needs
     permission: shortit.getlink
     default: op
permissions:
    shortit.*:
        description: Gives access to all commands
        children:
            shortit.autoshort: true
            shortit.getlink: true
            shortit.admin: true
        default: op
    shortit.admin:
        description: Allows the user ban, unban and view the users who have been banned from shortening URLs
        default: op
    shortit.short*:
        description: Gives access to autoshort and getlink
        children:
            shortit.autoshort: true
            shortit.getlink: true
        default: op
    shortit.autoshort:
        description: Lets you auto shorten URLs in the chat
        default: op
    shortit.getlink:
        description: Lets you short a URL using the command /link [url]
        default: op